version: "3.5"
services:
  getssl:
    build: .
    pull_policy: build
    container_name: getssl
    restart: unless-stopped
    network_mode: host
    stdin_open: true 
    tty: true
    environment:
      - TZ=Europe/London
      - MY_EMAIL=${MY_EMAIL}
      - MY_DOMAIN=${MY_DOMAIN}
      - MY_SANS=${MY_SANS}
      - MY_GODADDY_KEY=${MY_GODADDY_KEY}
      - MY_GODADDY_SECRET=${MY_GODADDY_SECRET}
    volumes:
      - getssl_data:/etc/letsencrypt:rw
      - /etc:/mnt/host_etc:rw
      - ssmtp_data:/etc/ssmtp:ro
#    healthcheck:
#      test: netstat -an | grep 1880; if [ 0 != $$? ]; then exit 1; fi;
##      test: ["CMD", "curl", "-f", "http://localhost:1880"]
#      interval: 30s
#      timeout: 20s
#      retries: 3
#      start_period: 40s
#   labels:
#      - "com.centurylinklabs.watchtower.enable=true"
volumes:
  getssl_data:
    external: true
  ssmtp_data:
    external: true
